CREATE DATABASE IF NOT EXISTS `pr2`;
CREATE DATABASE IF NOT EXISTS `pr2_testing`;
GRANT ALL PRIVILEGES ON `pr2`.* TO 'pr2-user'@'%';
GRANT ALL PRIVILEGES ON `pr2_testing`.* TO 'pr2-user'@'%';
FLUSH  PRIVILEGES;